### ISSUE TITLE
GameSession ScriptContext may be released after the application shuts down

### ISSUE THREAD

**Issue by pileofwolves** [pileofwolves/finmer#1]
During app shutdown, we do not yet properly dispose of the GameSession (`GameController.Session`). This means that the finalizer for GameSession (which releases the Lua context) will be called automatically in a semi-random order.

Depending on the actual order this happens in, the finalizer may be called *after* the Application has already been destroyed, which will cause a crash when the Lua context releases its ScriptableObjects, which in turn may try to access game systems.

Call stack might look something like this:
```
Finmer.Models.GameUI.Dispatcher.get()
Finmer.Models.GameUI.Log(string text, System.Windows.Media.Color color)
Finmer.Gameplay.ScriptableObject.LuaMetaGC(System.IntPtr state)
lua_close(lua_State * L)
Finmer.Gameplay.Scripting.ScriptContext.ReleaseUnmanagedResources()
Finmer.Gameplay.Scripting.ScriptContext.~ScriptContext()
```

**Proposed fix:**
Ensure that during application exit, we explicitly call `GameController.ExitSession()`. This will ensure everything game- and script-related is cleaned up before the application framework begins shutting down.

**Comment by Wh0Kn0w5** [comment]
For the application exit, is this on the OnExit found on the App.xaml.cs, and if so, should it be called before the base.OnExit()?

**Comment by pileofwolves** [comment]
Yep, `App.OnExit` should be a good place (before the `UserConfig.Save` call), that way it'll run regardless of how the game exits (window close button, Exit button in menus, etc).

**Comment by Wh0Kn0w5** [comment]
Ok, now that I've performed my mandatory random button-press and subsequent freakout, I've got the fix for this issue on a fork. Shall I make a pull request for merging it with master, or wait until I have the other issues resolved too?

**Comment by pileofwolves** [comment]
Please feel free to open a PR! One fix per branch/PR is ideal - if you want to do other things in the mean time, try using branches.
