### ISSUE TITLE
Crash when entering a patch scene as if it's a normal scene

### ISSUE THREAD

**Issue by pileofwolves** [pileofwolves/finmer#12]
**Reproduction steps:**
1. Start the game with the Core and Example01 (Injection Demo) modules loaded
2. Open the script console
3. Enter the command `SetScene("Patch_Example01_NoticeBoard")`
4. Observe that the game crashes

**Observed behavior:**
A patch scene is a scene asset that has been specially marked by its creator as being meant to be 'injected' into another scene. This is useful for modders, for example, since it enables someone to add new content into scenes that are originally provided by another content module. Beyond their patching functionality, patch scenes are not meant to be used directly by the player.

Using the `SetScene()` script function, it is possible to load a patch scene as if it were a fully-fledged scene of its own. This is not supported because patch scenes are not proper scenes themselves (they only add content to others) and as such are not meant to be visited directly. Currently, this causes a crash because `SceneScripted` tries to access the patch scene's cached scripts, but it does not have those (nor should it).

Note: This bug was introduced as a side-effect of the recent change that added the `ContentStore`, since before then, patch scenes were not recorded in the game's content list during loading, making them impossible to visit.

**Desired behavior:**
It should not be possible for the player to visit a patch scene in any way. Possible solutions include having `SceneScripted` or `GameplayScriptLibrary.ExportedSetScene()` throw an error using `luaL_error()`, or removing/withholding the patch scene from the `ContentStore` so that it can never be retrieved by `SceneScripted`. I am also open to alternative solutions.

**Comment by Wh0Kn0w5** [comment]
Currently seeing the crash as being caused by an ObjectReferenceException under the ```**LoadScript()**``` method in ```ScriptContext```

Namely that the ```CompiledScript``` variable "precompiled" is a null value. Would either of your two aforementioned fixes work with remedying that issue?

**Comment by pileofwolves** [comment]
Yes, that crash is a symptom of the problem, not the root cause. It tries to load the scene, but the scene data is invalid; the game shouldn't try to load it in the first place.

**Comment by Wh0Kn0w5** [comment]
So, I haven't seen much in the way of documentation about it, is there a specific naming scheme that patch scenes have to follow before they're able to work with the modular system, or will any name work and they just need to be an add-on to the main core module?

**Comment by pileofwolves** [comment]
Guilty as charged, this is missing documentation.

A scene can be marked as a patch in the Editor by clicking on its Root node, and ticking the 'Inject into another Scene' checkbox. It doesn't matter what module it's in (they'll work if they're in Core, too), and no naming scheme is required, though I prefer sticking to the `Patch_` prefix to visually distinguish them.

**Comment by Wh0Kn0w5** [comment]
Then in that case, even if the scene is named whatever, is there a value that the checkbox has that can be looked up in the script to see if it's checked or not, differentiating between a patch scene and normal scene.

It's my assumption that the user is able to set a custom scene properly, and that's it's only the patch scenes that need to be blocked, correct?

**Comment by pileofwolves** [comment]
The check box maps to the `AssetScene.Inject` property. If it's `true`, it's a patch. Those will need to be restricted in some way; regular scenes are, well, regular scenes, and should be loaded as normal.
