### ISSUE TITLE
Equipment box has wrong tooltip after item is swapped out

### ISSUE THREAD

**Issue by pileofwolves** [pileofwolves/finmer#13]
**Reproduction steps:**
1. Start the game
2. Run the script console command: `Player:GiveItem("A_ClothArmor");Player:GiveItem("A_LeatherArmor")`
3. Open the character sheet
4. Equip either armor item
5. Observe that the armor slot's tooltip is correct: it shows the item that was just equipped
6. Equip the other armor item, swapping them out
7. Observe that the armor slot's tooltip is incorrect: it shows the previous item

**Notes:**
This is likely caused by the `ItemTooltipView` caching the first tooltip it shows, and disregarding any data changes following that. In that case, the best solution for this is likely to ensure that when the DataContext of `ItemTooltipView` changes, any cached tooltip is discarded, such as by subscribing the view to the [DataContextChanged event](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.datacontextchanged?view=netframework-4.8). That way, it will be reconstructed on-demand whenever the user hovers over the new item.

**Comment by Wh0Kn0w5** [comment]
so, as far as previous examples to work with subscribing to the DataContextChanged event, I see something similar on the CombatantListItemView.xaml.cs  script for the CombatantListItemView_OnDataContextChaned() method. Should the subscription of the view to the DataContextChanged event act similarly to the Combatant subscription method?

**Comment by pileofwolves** [comment]
Yes, that'd be a good example I think. The view subscribes to the event in XAML (line 12). The CombatantListViewItem then does some incantations to change the object it receives notifications from. For the ItemTooltipView we don't really need that, I think it might just be sufficient to wipe the cached contents of the tooltip (that's `ItemInfoLabel.Inlines`), and then call `CreateTooltipContent` so it gets rebuilt.

In that case, the whole Loaded event handler (`Tooltip_OnLoaded`) can probably go out the window, since DataContextChanged does the same thing but better.

**Comment by Wh0Kn0w5** [comment]
Alright, I'm not sure what I'm doing wrong.

I've added a "DataContextChanged" to the XAML on the tooltip view, akin to the CombatantListItemView. I've also added in an ItemTooltipView_OnContextChanged to the xaml.cs for the tooltip as well. However, the method for OnContextChanged is showing as 0 references to it, and Visual studio is saying it's never called in the solution.

What needs to happen to get the tooltip view to properly register the OnContextChanged method like the CombatantListItemView does?

**Comment by pileofwolves** [comment]
Does the function get called, though? Visual Studio isn't always right about its warnings and suggestions, particularly with XAML if you're adding new code that hasn't been compiled yet.

What you're describing _sounds_ correct, so I can't say much more without a code sample. Feel free to open a draft PR if you want.
