### ISSUE TITLE
Missing visual style for ToggleButton

### ISSUE THREAD

**Issue by pileofwolves** [pileofwolves/finmer#14]
**Reproduction steps:**
1. Start the game
2. Add some items to the player's inventory (such as with the console command `Player:GiveItem("A_LeatherArmor")`)
3. Open the character sheet
4. Click on an item in the inventory
5. Observe the missing style on the Drop button (which is a ToggleButton)

**Notes:**
The ToggleButton does not have a proper visual style as compared to other UI components. Currently it appears to be using a simple default style from back in Finmer's early days.

ToggleButton should have a visual style similar to the regular Button's. It can likely be largely copied from Button (or, even better, reference Button as a base template), but may need some minor modification to account for ToggleButton's behavior: since ToggleButton remains pressed when clicked once, the 'pressed' visual state may need to be tweaked if it doesn't work out of the box.

**Comment by Wh0Kn0w5** [comment]
Ok, I believe I have the ToggleButton to a good degree to match the regular Button in terms of normal design.

However, the current IsChecked state has it in the old blue form. What did you have in mind for the color the button should stay as while checked and the secondary pop-up menu is displayed?

**Comment by pileofwolves** [comment]
I think the IsPressed and IsChecked state could share most properties, like colors. If IsChecked makes the button dark like IsPressed does, it should look 'pressed down' while activated, which is more or less what it's expected to do. IsPressed just needs to keep the scaling animations.

**Comment by Wh0Kn0w5** [comment]
So the IsPressed state uses a storyboard animation to scale the button down 10%, then reverts it with the ExitActions. When trying to directly copy the storyboard, the button does not stay scaled when checked.

I'm looking over the properties for the ToggleButton class to see if there's anything I can use in there, but the MS docs don't show a property involving scale specifically. There are Height/Width and maximums for that, but I'm not sure that's what you have in mind.

How do you suppose I can get the scale to perpetuate after the "press" is finished and is disabled when the button is no longer checked?

**Comment by pileofwolves** [comment]
So the button scales back up when the mouse is released, if I understand correctly? That's fine by me, since the scaling animation is intended more as feedback for the mouse press itself. If the button stays dark when checked, I'm happy.
