### ISSUE TITLE
Crash when reloading a scene from a soft transition

### ISSUE THREAD

**Issue by Wh0Kn0w5** [pileofwolves/finmer#21]
**Reproduction Steps:**

1. Start the game with Core loaded
2. Perform any activity that doesn't refresh the compass exits for the scene (Talk with Gabe, view Notice Board, etc.)
3. Leave the activity through the subsequent "Leave" option.
4. Observe that the game crashes.

**Observed Behavior**
For the town scenes, the Main node has an "AddLink" action on its script. When the calls to leave the activity and refresh the scene happen, the game attempts to add exits in directions that already exist, instead of overwriting the current values. This triggers an exception due to "An item with the same key has already been added."

**Comment by pileofwolves** [comment]
Thanks for the report!

Seems like I forgot to remove links entirely when interacting with something in a scene; it shouldn't be possible to directly use the compass when doing some activity like talking to Gabe. Oops. Even so, it shouldn't crash when adding a link to the same direction twice, either.

Will look into it.
