### ISSUE TITLE
Feature Request: Expand String replacement options for Creatures

### ISSUE THREAD

**Issue by Wh0Kn0w5** [pileofwolves/finmer#38]
Current build, only options are Always, Player on NPC, NPC on player and NPC on NPC. With this design, there cannot be unique strings for distinct events to occur between enemies and allies in combat.

Request that NPC on NPC be revamped to NPC on Creature and Creature on NPC for distinct string replacement.

**Comment by pileofwolves** [comment]
Thanks for raising this.

So what you need, is for a Creature to have separate string mapping rules for when they kill an NPC, versus when an NPC kills them, correct?

Would it be acceptable to have Creatures not differentiate between the exact NPC, just whether they instigated the action or not? so for example if there are two enemies and one ally in the combat, the same ally-kills-enemy text would be used for both enemies.

**Comment by Wh0Kn0w5** [comment]
For what I had in mind for my mod ideas, that combination would work.

For anyone who wants to play up a hypothetical rivalry situation, where one rival has distinct dialogue/script when they kill/eat the other the idea of a specific Creature being the victim and a different specific Creature being the killer/predator would add to complexity options.

I suppose there is the combat state scripts that could be used as well, but I don't know if they would bypass the built-in combat strings or not.

**Comment by pileofwolves** [comment]
The 'NPC rivalry' is a potential use case, I suppose, but I don't really see it happening in practice tbh, It would mean you have a combat with at least two enemies, and you want them to have separate strings relating to the ally (maybe vore, maybe any other combat text). I think that could be implemented more easily with a joint text where, I dunno, the two enemies gang up together on the ally.

With that in mind, it might be sufficient to extend the mapping rules to this:

- Always
- Player -> NPC
- NPC -> Player
- NPC -> NPC, if this creature was the instigator
- NPC -> NPC, if this creature was the target

I wonder if having a generic "NPC -> NPC regardless of who's who" rule would still be useful then.

**Comment by Wh0Kn0w5** [comment]
As per what I discussed in the external chat, depending on the string used, the current NPC -> NPC regardless of who's who is having some issues with the proper text displaying, given the context of it.

I think that rule wouldn't be useful anymore.
